# Generated by Django 4.1.4 on 2022-12-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=True, upload_to='media', verbose_name='Изображение')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('hashtags', models.CharField(max_length=20, verbose_name='Хештег')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
        ),
    ]
